name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Install packages        
      run: |
        sdkmanager "build-tools;33.0.2" "platforms;android-26" "platforms;android-34"
    - name: Build app
      run: |
        cd retrodrawing
        mvn --batch-mode clean install package
    - name: Read version
      run: |
        cd retrodrawing
        echo "GITHUB_DDVER=$(mvn -q org.apache.maven.plugins:maven-help-plugin:3.1.1:evaluate -Dexpression=project.version -DforceStdout)" >> $GITHUB_ENV
    - name: Build android
      run: |
        cd android-wrapper
        gradle --stacktrace -Pcartridge.artifactId=retrodrawing -Pcartridge.groupId=com.github.msx80.omicron -Pcartridge.version=$GITHUB_DDVER clean assembleRelease
    - uses: actions/upload-artifact@v4
      with:
        name: Unsigned retrodrawing.apk
        path: android-wrapper/app/build/outputs/apk/release/app-release-unsigned.apk
    - uses: ilharp/sign-android-release@v1
      name: Sign app APK
      id: sign_app
      with:
        releaseDir: android-wrapper/app/build/outputs/apk/release
        signingKey: ${{ secrets.SIGNING_KEY }}
        keyAlias: ${{ secrets.SIGNING_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_PASSWORD }}
        buildToolsVersion: 33.0.2
    - name: Rename apk
      run: |
        mv -v ${{steps.sign_app.outputs.signedFile}} retrodrawing.apk
    - uses: actions/upload-artifact@v4
      with:
        name: retrodrawing.apk
        path: retrodrawing.apk
    - name: Build desktop
      run: |
        cd desktop-mvn
        mvn --batch-mode -Dcartridge.artifactId=retrodrawing -Dcartridge.groupId=com.github.msx80.omicron -Dcartridge.version=$GITHUB_DDVER clean package
    - name: Deploy Desktop
      uses: actions/upload-artifact@v4
      with:
        name: 'retrodrawing-desktop.jar'
        path: desktop-mvn/target/retrodrawing-desktop.jar

    - name: Deploy cartridge
      uses: actions/upload-artifact@v4
      with:
        name: 'retrodrawing.omicron'
        path: retrodrawing/retrodrawing.omicron
